# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_integer <- function(x) {
    .Call('_epistasisGAGE_as_integer', PACKAGE = 'epistasisGAGE', x)
}

scalar_min <- function(x, y) {
    .Call('_epistasisGAGE_scalar_min', PACKAGE = 'epistasisGAGE', x, y)
}

scalar_max <- function(x, y) {
    .Call('_epistasisGAGE_scalar_max', PACKAGE = 'epistasisGAGE', x, y)
}

concat <- function(x, y) {
    .Call('_epistasisGAGE_concat', PACKAGE = 'epistasisGAGE', x, y)
}

concat_list <- function(x, y) {
    .Call('_epistasisGAGE_concat_list', PACKAGE = 'epistasisGAGE', x, y)
}

sort_by_order <- function(x, y, sort_type) {
    .Call('_epistasisGAGE_sort_by_order', PACKAGE = 'epistasisGAGE', x, y, sort_type)
}

seq_by2 <- function(l) {
    .Call('_epistasisGAGE_seq_by2', PACKAGE = 'epistasisGAGE', l)
}

unique_chrom_list <- function(chromosome_list, chrom_size) {
    .Call('_epistasisGAGE_unique_chrom_list', PACKAGE = 'epistasisGAGE', chromosome_list, chrom_size)
}

subset_matrix_cols <- function(in_matrix, cols) {
    .Call('_epistasisGAGE_subset_matrix_cols', PACKAGE = 'epistasisGAGE', in_matrix, cols)
}

subset_lmatrix_cols <- function(in_matrix, cols) {
    .Call('_epistasisGAGE_subset_lmatrix_cols', PACKAGE = 'epistasisGAGE', in_matrix, cols)
}

subset_matrix_rows <- function(in_matrix, rows) {
    .Call('_epistasisGAGE_subset_matrix_rows', PACKAGE = 'epistasisGAGE', in_matrix, rows)
}

subset_lmatrix_rows <- function(in_matrix, rows) {
    .Call('_epistasisGAGE_subset_lmatrix_rows', PACKAGE = 'epistasisGAGE', in_matrix, rows)
}

sign_scalar <- function(x) {
    .Call('_epistasisGAGE_sign_scalar', PACKAGE = 'epistasisGAGE', x)
}

subset_matrix <- function(in_matrix, rows, cols) {
    .Call('_epistasisGAGE_subset_matrix', PACKAGE = 'epistasisGAGE', in_matrix, rows, cols)
}

subset_lmatrix <- function(in_matrix, rows, cols) {
    .Call('_epistasisGAGE_subset_lmatrix', PACKAGE = 'epistasisGAGE', in_matrix, rows, cols)
}

weighted_sub_colsums <- function(in_mat, target_rows, target_cols, row_weights) {
    .Call('_epistasisGAGE_weighted_sub_colsums', PACKAGE = 'epistasisGAGE', in_mat, target_rows, target_cols, row_weights)
}

sub_rowsums_start <- function(in_mat, target_cols) {
    .Call('_epistasisGAGE_sub_rowsums_start', PACKAGE = 'epistasisGAGE', in_mat, target_cols)
}

sub_colsumsl <- function(in_mat, target_rows, target_cols) {
    .Call('_epistasisGAGE_sub_colsumsl', PACKAGE = 'epistasisGAGE', in_mat, target_rows, target_cols)
}

sub_rowsumsl <- function(in_mat, target_rows, target_cols) {
    .Call('_epistasisGAGE_sub_rowsumsl', PACKAGE = 'epistasisGAGE', in_mat, target_rows, target_cols)
}

n_pos_high_risk <- function(in_mat, target_rows, target_cols) {
    .Call('_epistasisGAGE_n_pos_high_risk', PACKAGE = 'epistasisGAGE', in_mat, target_rows, target_cols)
}

n_neg_high_risk <- function(in_mat, target_rows, target_cols) {
    .Call('_epistasisGAGE_n_neg_high_risk', PACKAGE = 'epistasisGAGE', in_mat, target_rows, target_cols)
}

sub_colmeans <- function(in_mat, target_rows, target_cols) {
    .Call('_epistasisGAGE_sub_colmeans', PACKAGE = 'epistasisGAGE', in_mat, target_rows, target_cols)
}

split_int_mat <- function(in_mat, in_vec, uni_in_vec) {
    .Call('_epistasisGAGE_split_int_mat', PACKAGE = 'epistasisGAGE', in_mat, in_vec, uni_in_vec)
}

split_logical_mat <- function(in_mat, in_vec, uni_in_vec) {
    .Call('_epistasisGAGE_split_logical_mat', PACKAGE = 'epistasisGAGE', in_mat, in_vec, uni_in_vec)
}

get_target_snps_ld_blocks <- function(target_snps_in, ld_block_vec) {
    .Call('_epistasisGAGE_get_target_snps_ld_blocks', PACKAGE = 'epistasisGAGE', target_snps_in, ld_block_vec)
}

find_high_risk <- function(n_target, n_pos, n_neg, neg_risk_int, pos_risk_int, case_data, comp, informative_families, target_snps) {
    .Call('_epistasisGAGE_find_high_risk', PACKAGE = 'epistasisGAGE', n_target, n_pos, n_neg, neg_risk_int, pos_risk_int, case_data, comp, informative_families, target_snps)
}

compute_dif_vecs <- function(case_genetic_data, comp_genetic_data, case_comp_dif, target_snps, cases_minus_complements, both_one_mat, weight_lookup, n_different_snps_weight = 2L, n_both_one_weight = 1L) {
    .Call('_epistasisGAGE_compute_dif_vecs', PACKAGE = 'epistasisGAGE', case_genetic_data, comp_genetic_data, case_comp_dif, target_snps, cases_minus_complements, both_one_mat, weight_lookup, n_different_snps_weight, n_both_one_weight)
}

chrom_fitness_score <- function(case_genetic_data_in, complement_genetic_data_in, case_comp_differences_in, target_snps_in, cases_minus_complements_in, both_one_mat_in, ld_block_vec, weight_lookup, case2_mat, case0_mat, comp2_mat, comp0_mat, n_different_snps_weight = 2L, n_both_one_weight = 1L, recessive_ref_prop = 0.75, recode_test_stat = 1.64, epi_test = FALSE, GxE = FALSE) {
    .Call('_epistasisGAGE_chrom_fitness_score', PACKAGE = 'epistasisGAGE', case_genetic_data_in, complement_genetic_data_in, case_comp_differences_in, target_snps_in, cases_minus_complements_in, both_one_mat_in, ld_block_vec, weight_lookup, case2_mat, case0_mat, comp2_mat, comp0_mat, n_different_snps_weight, n_both_one_weight, recessive_ref_prop, recode_test_stat, epi_test, GxE)
}

GxE_fitness_score <- function(case_genetic_data_list, complement_genetic_data_list, case_comp_differences_list, target_snps, cases_minus_complements_list, both_one_mat_list, ld_block_vec, weight_lookup, case2_mat_list, case0_mat_list, comp2_mat_list, comp0_mat_list, exposure_levels, exposure_risk_levels, n_different_snps_weight = 2L, n_both_one_weight = 1L, recessive_ref_prop = 0.75, recode_test_stat = 1.64, epi_test = FALSE, check_risk = TRUE) {
    .Call('_epistasisGAGE_GxE_fitness_score', PACKAGE = 'epistasisGAGE', case_genetic_data_list, complement_genetic_data_list, case_comp_differences_list, target_snps, cases_minus_complements_list, both_one_mat_list, ld_block_vec, weight_lookup, case2_mat_list, case0_mat_list, comp2_mat_list, comp0_mat_list, exposure_levels, exposure_risk_levels, n_different_snps_weight, n_both_one_weight, recessive_ref_prop, recode_test_stat, epi_test, check_risk)
}

chrom_fitness_list <- function(case_genetic_data, complement_genetic_data, case_comp_differences, chromosome_list, cases_minus_complements, both_one_mat, ld_block_vec, weight_lookup, case2_mat, case0_mat, comp2_mat, comp0_mat, n_different_snps_weight = 2L, n_both_one_weight = 1L, recessive_ref_prop = 0.75, recode_test_stat = 1.64, epi_test = FALSE) {
    .Call('_epistasisGAGE_chrom_fitness_list', PACKAGE = 'epistasisGAGE', case_genetic_data, complement_genetic_data, case_comp_differences, chromosome_list, cases_minus_complements, both_one_mat, ld_block_vec, weight_lookup, case2_mat, case0_mat, comp2_mat, comp0_mat, n_different_snps_weight, n_both_one_weight, recessive_ref_prop, recode_test_stat, epi_test)
}

GxE_fitness_list <- function(case_genetic_data_list, complement_genetic_data_list, case_comp_differences_list, chromosome_list, cases_minus_complements_list, both_one_mat_list, ld_block_vec, weight_lookup, case2_mat_list, case0_mat_list, comp2_mat_list, comp0_mat_list, exposure_levels, exposure_risk_levels, n_different_snps_weight = 2L, n_both_one_weight = 1L, recessive_ref_prop = 0.75, recode_test_stat = 1.64, epi_test = FALSE, check_risk = TRUE) {
    .Call('_epistasisGAGE_GxE_fitness_list', PACKAGE = 'epistasisGAGE', case_genetic_data_list, complement_genetic_data_list, case_comp_differences_list, chromosome_list, cases_minus_complements_list, both_one_mat_list, ld_block_vec, weight_lookup, case2_mat_list, case0_mat_list, comp2_mat_list, comp0_mat_list, exposure_levels, exposure_risk_levels, n_different_snps_weight, n_both_one_weight, recessive_ref_prop, recode_test_stat, epi_test, check_risk)
}

compute_population_fitness <- function(case_genetic_data, complement_genetic_data, case_comp_different, case_minus_comp, both_one_mat, ld_block_vec, chromosome_list, weight_lookup, case2_mat, case0_mat, comp2_mat, comp0_mat, case_genetic_data_list, complement_genetic_data_list, case_comp_different_list, case_minus_comp_list, both_one_mat_list, case2_mat_list, case0_mat_list, comp2_mat_list, comp0_mat_list, exposure_levels, exposure_risk_levels, n_different_snps_weight = 2L, n_both_one_weight = 1L, recessive_ref_prop = 0.75, recode_test_stat = 1.64, GxE = FALSE, check_risk = TRUE) {
    .Call('_epistasisGAGE_compute_population_fitness', PACKAGE = 'epistasisGAGE', case_genetic_data, complement_genetic_data, case_comp_different, case_minus_comp, both_one_mat, ld_block_vec, chromosome_list, weight_lookup, case2_mat, case0_mat, comp2_mat, comp0_mat, case_genetic_data_list, complement_genetic_data_list, case_comp_different_list, case_minus_comp_list, both_one_mat_list, case2_mat_list, case0_mat_list, comp2_mat_list, comp0_mat_list, exposure_levels, exposure_risk_levels, n_different_snps_weight, n_both_one_weight, recessive_ref_prop, recode_test_stat, GxE, check_risk)
}

find_top_chrom <- function(fitness_scores, chromosome_list, chromosome_size) {
    .Call('_epistasisGAGE_find_top_chrom', PACKAGE = 'epistasisGAGE', fitness_scores, chromosome_list, chromosome_size)
}

initiate_population <- function(n_candidate_snps, case_genetic_data, complement_genetic_data, case_comp_different, case_minus_comp, both_one_mat, ld_block_vec, n_chromosomes, chromosome_size, weight_lookup, case2_mat, case0_mat, comp2_mat, comp0_mat, case_genetic_data_list, complement_genetic_data_list, case_comp_different_list, case_minus_comp_list, both_one_mat_list, case2_mat_list, case0_mat_list, comp2_mat_list, comp0_mat_list, exposure_levels, exposure_risk_levels, n_different_snps_weight = 2L, n_both_one_weight = 1L, recessive_ref_prop = 0.75, recode_test_stat = 1.64, max_generations = 500L, initial_sample_duplicates = FALSE, GxE = FALSE, check_risk = TRUE) {
    .Call('_epistasisGAGE_initiate_population', PACKAGE = 'epistasisGAGE', n_candidate_snps, case_genetic_data, complement_genetic_data, case_comp_different, case_minus_comp, both_one_mat, ld_block_vec, n_chromosomes, chromosome_size, weight_lookup, case2_mat, case0_mat, comp2_mat, comp0_mat, case_genetic_data_list, complement_genetic_data_list, case_comp_different_list, case_minus_comp_list, both_one_mat_list, case2_mat_list, case0_mat_list, comp2_mat_list, comp0_mat_list, exposure_levels, exposure_risk_levels, n_different_snps_weight, n_both_one_weight, recessive_ref_prop, recode_test_stat, max_generations, initial_sample_duplicates, GxE, check_risk)
}

check_convergence <- function(island_cluster_size, island_populations) {
    .Call('_epistasisGAGE_check_convergence', PACKAGE = 'epistasisGAGE', island_cluster_size, island_populations)
}

check_max_gens <- function(island_populations, max_generations) {
    .Call('_epistasisGAGE_check_max_gens', PACKAGE = 'epistasisGAGE', island_populations, max_generations)
}

parse_input_data <- function(genetic_data_in, target_snps_in = NULL) {
    .Call('_epistasisGAGE_parse_input_data', PACKAGE = 'epistasisGAGE', genetic_data_in, target_snps_in)
}

run_GADGETS <- function(island_cluster_size, n_migrations, ld_block_vec, n_chromosomes, chromosome_size, weight_lookup, snp_chisq, genetic_data_in, exposure_levels_in = NULL, exposure_risk_levels_in = NULL, exposure_in = NULL, n_different_snps_weight = 2L, n_both_one_weight = 1L, migration_interval = 50L, gen_same_fitness = 50L, max_generations = 500L, initial_sample_duplicates = FALSE, crossover_prop = 0.8, recessive_ref_prop = 0.75, recode_test_stat = 1.64) {
    .Call('_epistasisGAGE_run_GADGETS', PACKAGE = 'epistasisGAGE', island_cluster_size, n_migrations, ld_block_vec, n_chromosomes, chromosome_size, weight_lookup, snp_chisq, genetic_data_in, exposure_levels_in, exposure_risk_levels_in, exposure_in, n_different_snps_weight, n_both_one_weight, migration_interval, gen_same_fitness, max_generations, initial_sample_duplicates, crossover_prop, recessive_ref_prop, recode_test_stat)
}

epistasis_test_permute <- function(case_inf, comp_inf, target_snps_ld_blocks, uni_ld_blocks, n_families, weight_lookup, n_different_snps_weight = 2L, n_both_one_weight = 1L, recessive_ref_prop = 0.75, recode_test_stat = 1.64) {
    .Call('_epistasisGAGE_epistasis_test_permute', PACKAGE = 'epistasisGAGE', case_inf, comp_inf, target_snps_ld_blocks, uni_ld_blocks, n_families, weight_lookup, n_different_snps_weight, n_both_one_weight, recessive_ref_prop, recode_test_stat)
}

epistasis_test_null_scores <- function(n_permutes, case_inf, comp_inf, target_snps_ld_blocks, uni_ld_blocks, n_families, weight_lookup, n_different_snps_weight = 2L, n_both_one_weight = 1L, recessive_ref_prop = 0.75, recode_test_stat = 1.64) {
    .Call('_epistasisGAGE_epistasis_test_null_scores', PACKAGE = 'epistasisGAGE', n_permutes, case_inf, comp_inf, target_snps_ld_blocks, uni_ld_blocks, n_families, weight_lookup, n_different_snps_weight, n_both_one_weight, recessive_ref_prop, recode_test_stat)
}

epistasis_test <- function(snp_cols, ld_block_vec, genetic_data_list, n_permutes = 10000L, n_different_snps_weight = 2L, n_both_one_weight = 1L, weight_function_int = 2L, recessive_ref_prop = 0.75, recode_test_stat = 1.64, warn = TRUE) {
    .Call('_epistasisGAGE_epistasis_test', PACKAGE = 'epistasisGAGE', snp_cols, ld_block_vec, genetic_data_list, n_permutes, n_different_snps_weight, n_both_one_weight, weight_function_int, recessive_ref_prop, recode_test_stat, warn)
}

GxE_test <- function(snp_cols, ld_block_vec, genetic_data_list, exposure, exposure_levels, exposure_risk_levels, n_permutes = 10000L, n_different_snps_weight = 2L, n_both_one_weight = 1L, weight_function_int = 2L, recessive_ref_prop = 0.75, recode_test_stat = 1.64) {
    .Call('_epistasisGAGE_GxE_test', PACKAGE = 'epistasisGAGE', snp_cols, ld_block_vec, genetic_data_list, exposure, exposure_levels, exposure_risk_levels, n_permutes, n_different_snps_weight, n_both_one_weight, weight_function_int, recessive_ref_prop, recode_test_stat)
}

n2log_epistasis_pvals <- function(chromosome_list, ld_block_vec, in_data_list, n_permutes = 10000L, n_different_snps_weight = 2L, n_both_one_weight = 1L, weight_function_int = 2L, recessive_ref_prop = 0.75, recode_test_stat = 1.64, exposure_in = NULL, exposure_levels_in = NULL, exposure_risk_levels_in = NULL) {
    .Call('_epistasisGAGE_n2log_epistasis_pvals', PACKAGE = 'epistasisGAGE', chromosome_list, ld_block_vec, in_data_list, n_permutes, n_different_snps_weight, n_both_one_weight, weight_function_int, recessive_ref_prop, recode_test_stat, exposure_in, exposure_levels_in, exposure_risk_levels_in)
}

create_permuted_data <- function(genetic_data_list, flip_these_families, trio_study) {
    invisible(.Call('_epistasisGAGE_create_permuted_data', PACKAGE = 'epistasisGAGE', genetic_data_list, flip_these_families, trio_study))
}

